name: Create Plugin Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare plugin folder structure
        run: |
          mkdir -p build/gutenberg-responsive-tables
          rsync -av --delete --exclude-from=.distignore ./ build/gutenberg-responsive-tables/

      - name: Create production zip
        run: |
          cd build
          zip -r ../gutenberg-responsive-tables.zip gutenberg-responsive-tables

      - name: Create GitHub Release + attach ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: gutenberg-responsive-tables.zip
          generate_release_notes: true
          draft: false